twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        tracking_code: 123456
    form_themes:
        ['bootstrap_4_layout.html.twig']
